// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/controlplane.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamBackendsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The backend pool group this data plane instance serves traffic for,
	// e.g. "web-tier" or "api-tier". Lets one control plane serve multiple
	// independent proxy fleets.
	Group string `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	// Human-readable identifier for the connecting data plane instance,
	// used only for control plane logging/observability.
	InstanceId    string `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamBackendsRequest) Reset() {
	*x = StreamBackendsRequest{}
	mi := &file_proto_controlplane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamBackendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamBackendsRequest) ProtoMessage() {}

func (x *StreamBackendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamBackendsRequest.ProtoReflect.Descriptor instead.
func (*StreamBackendsRequest) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{0}
}

func (x *StreamBackendsRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *StreamBackendsRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type Backend struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Address string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // host:port
	// Relative capacity weight for weighted load balancing. Defaults to 1
	// when unset/zero.
	Weight        int32 `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Backend) Reset() {
	*x = Backend{}
	mi := &file_proto_controlplane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Backend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Backend) ProtoMessage() {}

func (x *Backend) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Backend.ProtoReflect.Descriptor instead.
func (*Backend) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{1}
}

func (x *Backend) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Backend) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type BackendSet struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Group    string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Backends []*Backend             `protobuf:"bytes,2,rep,name=backends,proto3" json:"backends,omitempty"`
	// Monotonically increasing version number for this group's backend set.
	// Lets the data plane detect and ignore stale/out-of-order updates.
	Version int64 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	// Load-balancing algorithm the data plane should use to select among
	// these backends: "round_robin" (default, weighted), "least_connections"
	// (weighted by outstanding request count), or "random" (weighted).
	// Unset/unrecognised values fall back to round_robin.
	Algorithm string `protobuf:"bytes,4,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	// Whether cookie-based session affinity is enabled for this group. When
	// true, the data plane pins a client to whichever backend it was last
	// routed to (via sticky_cookie_name) as long as that backend remains
	// healthy and part of the group, falling back to the normal algorithm
	// otherwise.
	Sticky bool `protobuf:"varint,5,opt,name=sticky,proto3" json:"sticky,omitempty"`
	// Name of the cookie used to carry session affinity. Only meaningful
	// when sticky is true; the data plane applies a default if unset.
	StickyCookieName string `protobuf:"bytes,6,opt,name=sticky_cookie_name,json=stickyCookieName,proto3" json:"sticky_cookie_name,omitempty"`
	// How long the affinity cookie should live, refreshed on every request
	// it's used for. Only meaningful when sticky is true; the data plane
	// applies a default if unset/zero.
	StickyTtlSeconds int64 `protobuf:"varint,7,opt,name=sticky_ttl_seconds,json=stickyTtlSeconds,proto3" json:"sticky_ttl_seconds,omitempty"`
	// Per-client request rate limit for this group, in requests per second.
	// 0 (default) disables rate limiting. The data plane enforces this with
	// a token bucket keyed on client IP; a client exceeding the rate gets
	// HTTP 429. L7 (http) mode only.
	RateLimitRps float64 `protobuf:"fixed64,8,opt,name=rate_limit_rps,json=rateLimitRps,proto3" json:"rate_limit_rps,omitempty"`
	// Maximum burst size (token-bucket depth) allowed above the steady
	// rate_limit_rps. 0 lets the data plane apply a sensible default
	// (equal to the rate) when rate limiting is enabled.
	RateLimitBurst int32 `protobuf:"varint,9,opt,name=rate_limit_burst,json=rateLimitBurst,proto3" json:"rate_limit_burst,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BackendSet) Reset() {
	*x = BackendSet{}
	mi := &file_proto_controlplane_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendSet) ProtoMessage() {}

func (x *BackendSet) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendSet.ProtoReflect.Descriptor instead.
func (*BackendSet) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{2}
}

func (x *BackendSet) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *BackendSet) GetBackends() []*Backend {
	if x != nil {
		return x.Backends
	}
	return nil
}

func (x *BackendSet) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *BackendSet) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *BackendSet) GetSticky() bool {
	if x != nil {
		return x.Sticky
	}
	return false
}

func (x *BackendSet) GetStickyCookieName() string {
	if x != nil {
		return x.StickyCookieName
	}
	return ""
}

func (x *BackendSet) GetStickyTtlSeconds() int64 {
	if x != nil {
		return x.StickyTtlSeconds
	}
	return 0
}

func (x *BackendSet) GetRateLimitRps() float64 {
	if x != nil {
		return x.RateLimitRps
	}
	return 0
}

func (x *BackendSet) GetRateLimitBurst() int32 {
	if x != nil {
		return x.RateLimitBurst
	}
	return 0
}

type BackendHealth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // host:port, matches Backend.address
	Healthy       bool                   `protobuf:"varint,2,opt,name=healthy,proto3" json:"healthy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackendHealth) Reset() {
	*x = BackendHealth{}
	mi := &file_proto_controlplane_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendHealth) ProtoMessage() {}

func (x *BackendHealth) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendHealth.ProtoReflect.Descriptor instead.
func (*BackendHealth) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{3}
}

func (x *BackendHealth) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *BackendHealth) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

type HealthReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	InstanceId    string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"` // which data plane instance this report is from
	Backends      []*BackendHealth       `protobuf:"bytes,3,rep,name=backends,proto3" json:"backends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthReport) Reset() {
	*x = HealthReport{}
	mi := &file_proto_controlplane_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthReport) ProtoMessage() {}

func (x *HealthReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthReport.ProtoReflect.Descriptor instead.
func (*HealthReport) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{4}
}

func (x *HealthReport) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *HealthReport) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *HealthReport) GetBackends() []*BackendHealth {
	if x != nil {
		return x.Backends
	}
	return nil
}

type HealthReportAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthReportAck) Reset() {
	*x = HealthReportAck{}
	mi := &file_proto_controlplane_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthReportAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthReportAck) ProtoMessage() {}

func (x *HealthReportAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthReportAck.ProtoReflect.Descriptor instead.
func (*HealthReportAck) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{5}
}

type StreamRoutesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human-readable identifier for the connecting data plane instance,
	// used only for control plane logging/observability.
	InstanceId    string `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRoutesRequest) Reset() {
	*x = StreamRoutesRequest{}
	mi := &file_proto_controlplane_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRoutesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRoutesRequest) ProtoMessage() {}

func (x *StreamRoutesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRoutesRequest.ProtoReflect.Descriptor instead.
func (*StreamRoutesRequest) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{6}
}

func (x *StreamRoutesRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type Route struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Host to match, exact string. "*" or empty matches any host — a
	// data plane with a single route relying on the default group
	// shouldn't need to specify a host at all.
	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	// Path prefix to match, e.g. "/api/". "/" matches every path.
	// Evaluated as a literal prefix, not a pattern language — kept
	// deliberately simple for a first cut of L7 routing.
	PathPrefix string `protobuf:"bytes,2,opt,name=path_prefix,json=pathPrefix,proto3" json:"path_prefix,omitempty"`
	// HTTP methods this rule applies to. Empty means any method.
	Methods []string `protobuf:"bytes,3,rep,name=methods,proto3" json:"methods,omitempty"`
	// Backend group a matching request is proxied to. Used when `split`
	// is empty (the common single-target case).
	TargetGroup string `protobuf:"bytes,4,opt,name=target_group,json=targetGroup,proto3" json:"target_group,omitempty"`
	// Display name/comment for the admin UI; not evaluated.
	Name string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	// Weighted traffic split: when non-empty, a matching request is sent
	// to one of these groups chosen by weight (e.g. 90/10 stable/canary)
	// rather than always to target_group. When empty, target_group is
	// used. A single-entry split is equivalent to target_group.
	Split []*RouteTarget `protobuf:"bytes,6,rep,name=split,proto3" json:"split,omitempty"`
	// Request/response rewrites applied when this rule matches, before the
	// request is proxied. All are optional; an empty rewrite is a no-op.
	Rewrite *RouteRewrite `protobuf:"bytes,7,opt,name=rewrite,proto3" json:"rewrite,omitempty"`
	// Edge authentication required on matched requests, checked before the
	// request is proxied to a backend. Nil/unset means no auth (open route).
	Auth *RouteAuth `protobuf:"bytes,8,opt,name=auth,proto3" json:"auth,omitempty"`
	// Additional request-header conditions that must ALL match (AND
	// semantics) on top of host/path/method. Empty means no header
	// condition. Lets a rule route on e.g. `X-Api-Version: 2` or the
	// presence of a header regardless of value.
	HeaderMatches []*HeaderMatch `protobuf:"bytes,9,rep,name=header_matches,json=headerMatches,proto3" json:"header_matches,omitempty"`
	// Additional query-parameter conditions that must ALL match (AND
	// semantics). Empty means no query condition. Lets a rule route on
	// e.g. `?canary=true` or the presence of a `debug` parameter.
	QueryMatches  []*QueryMatch `protobuf:"bytes,10,rep,name=query_matches,json=queryMatches,proto3" json:"query_matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_proto_controlplane_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{7}
}

func (x *Route) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Route) GetPathPrefix() string {
	if x != nil {
		return x.PathPrefix
	}
	return ""
}

func (x *Route) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

func (x *Route) GetTargetGroup() string {
	if x != nil {
		return x.TargetGroup
	}
	return ""
}

func (x *Route) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Route) GetSplit() []*RouteTarget {
	if x != nil {
		return x.Split
	}
	return nil
}

func (x *Route) GetRewrite() *RouteRewrite {
	if x != nil {
		return x.Rewrite
	}
	return nil
}

func (x *Route) GetAuth() *RouteAuth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *Route) GetHeaderMatches() []*HeaderMatch {
	if x != nil {
		return x.HeaderMatches
	}
	return nil
}

func (x *Route) GetQueryMatches() []*QueryMatch {
	if x != nil {
		return x.QueryMatches
	}
	return nil
}

// HeaderMatch is one request-header condition on a route. The named
// header must be present; when value is non-empty it must also equal
// value (case-insensitive on the header name per HTTP; the value
// comparison is case-sensitive). When value is empty, mere presence of
// the header satisfies the condition.
type HeaderMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeaderMatch) Reset() {
	*x = HeaderMatch{}
	mi := &file_proto_controlplane_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderMatch) ProtoMessage() {}

func (x *HeaderMatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderMatch.ProtoReflect.Descriptor instead.
func (*HeaderMatch) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{8}
}

func (x *HeaderMatch) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HeaderMatch) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// QueryMatch is one query-parameter condition on a route. The named
// query parameter must be present; when value is non-empty it must also
// equal value (both name and value compared case-sensitively, as query
// strings are). When value is empty, mere presence satisfies it.
type QueryMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryMatch) Reset() {
	*x = QueryMatch{}
	mi := &file_proto_controlplane_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMatch) ProtoMessage() {}

func (x *QueryMatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMatch.ProtoReflect.Descriptor instead.
func (*QueryMatch) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{9}
}

func (x *QueryMatch) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QueryMatch) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// RouteRewrite describes header and path transformations applied to a
// matched request (and its response). Every field is optional.
type RouteRewrite struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Request headers to set (overwriting any existing value). Map of
	// header name -> value.
	SetRequestHeaders map[string]string `protobuf:"bytes,1,rep,name=set_request_headers,json=setRequestHeaders,proto3" json:"set_request_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Request header names to remove before proxying to the backend.
	RemoveRequestHeaders []string `protobuf:"bytes,2,rep,name=remove_request_headers,json=removeRequestHeaders,proto3" json:"remove_request_headers,omitempty"`
	// Response headers to set on the way back to the client.
	SetResponseHeaders map[string]string `protobuf:"bytes,3,rep,name=set_response_headers,json=setResponseHeaders,proto3" json:"set_response_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Response header names to remove from the backend's response.
	RemoveResponseHeaders []string `protobuf:"bytes,4,rep,name=remove_response_headers,json=removeResponseHeaders,proto3" json:"remove_response_headers,omitempty"`
	// If non-empty, this literal prefix is stripped from the request path
	// before proxying (e.g. strip "/api" so the backend sees "/v1/x" for a
	// request to "/api/v1/x"). Applied before add_path_prefix.
	StripPathPrefix string `protobuf:"bytes,5,opt,name=strip_path_prefix,json=stripPathPrefix,proto3" json:"strip_path_prefix,omitempty"`
	// If non-empty, this literal prefix is prepended to the request path
	// before proxying. Applied after strip_path_prefix.
	AddPathPrefix string `protobuf:"bytes,6,opt,name=add_path_prefix,json=addPathPrefix,proto3" json:"add_path_prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteRewrite) Reset() {
	*x = RouteRewrite{}
	mi := &file_proto_controlplane_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteRewrite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteRewrite) ProtoMessage() {}

func (x *RouteRewrite) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteRewrite.ProtoReflect.Descriptor instead.
func (*RouteRewrite) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{10}
}

func (x *RouteRewrite) GetSetRequestHeaders() map[string]string {
	if x != nil {
		return x.SetRequestHeaders
	}
	return nil
}

func (x *RouteRewrite) GetRemoveRequestHeaders() []string {
	if x != nil {
		return x.RemoveRequestHeaders
	}
	return nil
}

func (x *RouteRewrite) GetSetResponseHeaders() map[string]string {
	if x != nil {
		return x.SetResponseHeaders
	}
	return nil
}

func (x *RouteRewrite) GetRemoveResponseHeaders() []string {
	if x != nil {
		return x.RemoveResponseHeaders
	}
	return nil
}

func (x *RouteRewrite) GetStripPathPrefix() string {
	if x != nil {
		return x.StripPathPrefix
	}
	return ""
}

func (x *RouteRewrite) GetAddPathPrefix() string {
	if x != nil {
		return x.AddPathPrefix
	}
	return ""
}

// RouteAuth describes edge authentication enforced on a matched request
// before it is proxied. Exactly one mode is active, selected by `mode`.
type RouteAuth struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Mode: "" or "none" (open), "api_key", or "jwt".
	Mode string `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	// api_key mode: the request must present one of api_keys in the header
	// named api_key_header (default "X-API-Key").
	ApiKeys      []string `protobuf:"bytes,2,rep,name=api_keys,json=apiKeys,proto3" json:"api_keys,omitempty"`
	ApiKeyHeader string   `protobuf:"bytes,3,opt,name=api_key_header,json=apiKeyHeader,proto3" json:"api_key_header,omitempty"`
	// jwt mode: the bearer token in the Authorization header must be a valid
	// JWT. hmac_secret validates HS256/384/512 tokens; if empty,
	// rsa_public_key_pem (PEM-encoded) validates RS256/384/512 tokens.
	// Optional expected issuer/audience are enforced when set.
	HmacSecret       string `protobuf:"bytes,4,opt,name=hmac_secret,json=hmacSecret,proto3" json:"hmac_secret,omitempty"`
	RsaPublicKeyPem  string `protobuf:"bytes,5,opt,name=rsa_public_key_pem,json=rsaPublicKeyPem,proto3" json:"rsa_public_key_pem,omitempty"`
	ExpectedIssuer   string `protobuf:"bytes,6,opt,name=expected_issuer,json=expectedIssuer,proto3" json:"expected_issuer,omitempty"`
	ExpectedAudience string `protobuf:"bytes,7,opt,name=expected_audience,json=expectedAudience,proto3" json:"expected_audience,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RouteAuth) Reset() {
	*x = RouteAuth{}
	mi := &file_proto_controlplane_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteAuth) ProtoMessage() {}

func (x *RouteAuth) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteAuth.ProtoReflect.Descriptor instead.
func (*RouteAuth) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{11}
}

func (x *RouteAuth) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *RouteAuth) GetApiKeys() []string {
	if x != nil {
		return x.ApiKeys
	}
	return nil
}

func (x *RouteAuth) GetApiKeyHeader() string {
	if x != nil {
		return x.ApiKeyHeader
	}
	return ""
}

func (x *RouteAuth) GetHmacSecret() string {
	if x != nil {
		return x.HmacSecret
	}
	return ""
}

func (x *RouteAuth) GetRsaPublicKeyPem() string {
	if x != nil {
		return x.RsaPublicKeyPem
	}
	return ""
}

func (x *RouteAuth) GetExpectedIssuer() string {
	if x != nil {
		return x.ExpectedIssuer
	}
	return ""
}

func (x *RouteAuth) GetExpectedAudience() string {
	if x != nil {
		return x.ExpectedAudience
	}
	return ""
}

// RouteTarget is one weighted destination of a canary/split route rule.
type RouteTarget struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Backend group this share of the traffic is sent to.
	Group string `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	// Relative weight of this target within the rule's split. Defaults to
	// 1 when unset/zero. A target's share is its weight over the sum of
	// all the rule's target weights.
	Weight        int32 `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteTarget) Reset() {
	*x = RouteTarget{}
	mi := &file_proto_controlplane_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteTarget) ProtoMessage() {}

func (x *RouteTarget) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteTarget.ProtoReflect.Descriptor instead.
func (*RouteTarget) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{12}
}

func (x *RouteTarget) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *RouteTarget) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type RouteTable struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Rules in evaluation order — the data plane checks them top to bottom
	// and uses the first match. A request matching no rule falls back to
	// the data plane's own -group flag, so an instance with an empty (or
	// unreachable) route table keeps behaving exactly as it did before L7
	// routing existed.
	Routes []*Route `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	// Monotonically increasing version number, mirroring BackendSet.version
	// — lets the data plane detect and ignore stale/out-of-order updates.
	Version       int64 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteTable) Reset() {
	*x = RouteTable{}
	mi := &file_proto_controlplane_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteTable) ProtoMessage() {}

func (x *RouteTable) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteTable.ProtoReflect.Descriptor instead.
func (*RouteTable) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{13}
}

func (x *RouteTable) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *RouteTable) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type GroupMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Group string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	// Counts since this instance's process start (or since the last
	// report — the control plane treats these as point-in-time gauges of
	// "requests seen so far", deriving a rate itself rather than the data
	// plane pre-computing one, since the report interval is configurable).
	RequestsTotal     int64 `protobuf:"varint,2,opt,name=requests_total,json=requestsTotal,proto3" json:"requests_total,omitempty"`
	Errors_5XxTotal   int64 `protobuf:"varint,3,opt,name=errors_5xx_total,json=errors5xxTotal,proto3" json:"errors_5xx_total,omitempty"`
	ActiveConnections int64 `protobuf:"varint,4,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	// Average request duration in milliseconds, over the reporting
	// interval since the last report — not cumulative like the counts
	// above, since an all-time average would smooth away exactly the
	// recent-latency-spike signal this exists to surface.
	AvgDurationMs float64 `protobuf:"fixed64,5,opt,name=avg_duration_ms,json=avgDurationMs,proto3" json:"avg_duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMetrics) Reset() {
	*x = GroupMetrics{}
	mi := &file_proto_controlplane_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMetrics) ProtoMessage() {}

func (x *GroupMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMetrics.ProtoReflect.Descriptor instead.
func (*GroupMetrics) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{14}
}

func (x *GroupMetrics) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *GroupMetrics) GetRequestsTotal() int64 {
	if x != nil {
		return x.RequestsTotal
	}
	return 0
}

func (x *GroupMetrics) GetErrors_5XxTotal() int64 {
	if x != nil {
		return x.Errors_5XxTotal
	}
	return 0
}

func (x *GroupMetrics) GetActiveConnections() int64 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *GroupMetrics) GetAvgDurationMs() float64 {
	if x != nil {
		return x.AvgDurationMs
	}
	return 0
}

type MetricsReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Groups        []*GroupMetrics        `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsReport) Reset() {
	*x = MetricsReport{}
	mi := &file_proto_controlplane_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsReport) ProtoMessage() {}

func (x *MetricsReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsReport.ProtoReflect.Descriptor instead.
func (*MetricsReport) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{15}
}

func (x *MetricsReport) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *MetricsReport) GetGroups() []*GroupMetrics {
	if x != nil {
		return x.Groups
	}
	return nil
}

type MetricsReportAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsReportAck) Reset() {
	*x = MetricsReportAck{}
	mi := &file_proto_controlplane_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsReportAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsReportAck) ProtoMessage() {}

func (x *MetricsReportAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsReportAck.ProtoReflect.Descriptor instead.
func (*MetricsReportAck) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{16}
}

var File_proto_controlplane_proto protoreflect.FileDescriptor

const file_proto_controlplane_proto_rawDesc = "" +
	"\n" +
	"\x18proto/controlplane.proto\x12\fcontrolplane\"N\n" +
	"\x15StreamBackendsRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\";\n" +
	"\aBackend\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\x05R\x06weight\"\xd1\x02\n" +
	"\n" +
	"BackendSet\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x121\n" +
	"\bbackends\x18\x02 \x03(\v2\x15.controlplane.BackendR\bbackends\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\x12\x1c\n" +
	"\talgorithm\x18\x04 \x01(\tR\talgorithm\x12\x16\n" +
	"\x06sticky\x18\x05 \x01(\bR\x06sticky\x12,\n" +
	"\x12sticky_cookie_name\x18\x06 \x01(\tR\x10stickyCookieName\x12,\n" +
	"\x12sticky_ttl_seconds\x18\a \x01(\x03R\x10stickyTtlSeconds\x12$\n" +
	"\x0erate_limit_rps\x18\b \x01(\x01R\frateLimitRps\x12(\n" +
	"\x10rate_limit_burst\x18\t \x01(\x05R\x0erateLimitBurst\"C\n" +
	"\rBackendHealth\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x18\n" +
	"\ahealthy\x18\x02 \x01(\bR\ahealthy\"~\n" +
	"\fHealthReport\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x127\n" +
	"\bbackends\x18\x03 \x03(\v2\x1b.controlplane.BackendHealthR\bbackends\"\x11\n" +
	"\x0fHealthReportAck\"6\n" +
	"\x13StreamRoutesRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\"\xa2\x03\n" +
	"\x05Route\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x1f\n" +
	"\vpath_prefix\x18\x02 \x01(\tR\n" +
	"pathPrefix\x12\x18\n" +
	"\amethods\x18\x03 \x03(\tR\amethods\x12!\n" +
	"\ftarget_group\x18\x04 \x01(\tR\vtargetGroup\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12/\n" +
	"\x05split\x18\x06 \x03(\v2\x19.controlplane.RouteTargetR\x05split\x124\n" +
	"\arewrite\x18\a \x01(\v2\x1a.controlplane.RouteRewriteR\arewrite\x12+\n" +
	"\x04auth\x18\b \x01(\v2\x17.controlplane.RouteAuthR\x04auth\x12@\n" +
	"\x0eheader_matches\x18\t \x03(\v2\x19.controlplane.HeaderMatchR\rheaderMatches\x12=\n" +
	"\rquery_matches\x18\n" +
	" \x03(\v2\x18.controlplane.QueryMatchR\fqueryMatches\"7\n" +
	"\vHeaderMatch\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"6\n" +
	"\n" +
	"QueryMatch\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xa6\x04\n" +
	"\fRouteRewrite\x12a\n" +
	"\x13set_request_headers\x18\x01 \x03(\v21.controlplane.RouteRewrite.SetRequestHeadersEntryR\x11setRequestHeaders\x124\n" +
	"\x16remove_request_headers\x18\x02 \x03(\tR\x14removeRequestHeaders\x12d\n" +
	"\x14set_response_headers\x18\x03 \x03(\v22.controlplane.RouteRewrite.SetResponseHeadersEntryR\x12setResponseHeaders\x126\n" +
	"\x17remove_response_headers\x18\x04 \x03(\tR\x15removeResponseHeaders\x12*\n" +
	"\x11strip_path_prefix\x18\x05 \x01(\tR\x0fstripPathPrefix\x12&\n" +
	"\x0fadd_path_prefix\x18\x06 \x01(\tR\raddPathPrefix\x1aD\n" +
	"\x16SetRequestHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aE\n" +
	"\x17SetResponseHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x84\x02\n" +
	"\tRouteAuth\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x19\n" +
	"\bapi_keys\x18\x02 \x03(\tR\aapiKeys\x12$\n" +
	"\x0eapi_key_header\x18\x03 \x01(\tR\fapiKeyHeader\x12\x1f\n" +
	"\vhmac_secret\x18\x04 \x01(\tR\n" +
	"hmacSecret\x12+\n" +
	"\x12rsa_public_key_pem\x18\x05 \x01(\tR\x0frsaPublicKeyPem\x12'\n" +
	"\x0fexpected_issuer\x18\x06 \x01(\tR\x0eexpectedIssuer\x12+\n" +
	"\x11expected_audience\x18\a \x01(\tR\x10expectedAudience\";\n" +
	"\vRouteTarget\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\x05R\x06weight\"S\n" +
	"\n" +
	"RouteTable\x12+\n" +
	"\x06routes\x18\x01 \x03(\v2\x13.controlplane.RouteR\x06routes\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\"\xcc\x01\n" +
	"\fGroupMetrics\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12%\n" +
	"\x0erequests_total\x18\x02 \x01(\x03R\rrequestsTotal\x12(\n" +
	"\x10errors_5xx_total\x18\x03 \x01(\x03R\x0eerrors5xxTotal\x12-\n" +
	"\x12active_connections\x18\x04 \x01(\x03R\x11activeConnections\x12&\n" +
	"\x0favg_duration_ms\x18\x05 \x01(\x01R\ravgDurationMs\"d\n" +
	"\rMetricsReport\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x122\n" +
	"\x06groups\x18\x02 \x03(\v2\x1a.controlplane.GroupMetricsR\x06groups\"\x12\n" +
	"\x10MetricsReportAck2\xc9\x02\n" +
	"\fControlPlane\x12Q\n" +
	"\x0eStreamBackends\x12#.controlplane.StreamBackendsRequest\x1a\x18.controlplane.BackendSet0\x01\x12I\n" +
	"\fReportHealth\x12\x1a.controlplane.HealthReport\x1a\x1d.controlplane.HealthReportAck\x12M\n" +
	"\fStreamRoutes\x12!.controlplane.StreamRoutesRequest\x1a\x18.controlplane.RouteTable0\x01\x12L\n" +
	"\rReportMetrics\x12\x1b.controlplane.MetricsReport\x1a\x1e.controlplane.MetricsReportAckB&Z$github.com/Josephfell/Jbalance/protob\x06proto3"

var (
	file_proto_controlplane_proto_rawDescOnce sync.Once
	file_proto_controlplane_proto_rawDescData []byte
)

func file_proto_controlplane_proto_rawDescGZIP() []byte {
	file_proto_controlplane_proto_rawDescOnce.Do(func() {
		file_proto_controlplane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_controlplane_proto_rawDesc), len(file_proto_controlplane_proto_rawDesc)))
	})
	return file_proto_controlplane_proto_rawDescData
}

var file_proto_controlplane_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_controlplane_proto_goTypes = []any{
	(*StreamBackendsRequest)(nil), // 0: controlplane.StreamBackendsRequest
	(*Backend)(nil),               // 1: controlplane.Backend
	(*BackendSet)(nil),            // 2: controlplane.BackendSet
	(*BackendHealth)(nil),         // 3: controlplane.BackendHealth
	(*HealthReport)(nil),          // 4: controlplane.HealthReport
	(*HealthReportAck)(nil),       // 5: controlplane.HealthReportAck
	(*StreamRoutesRequest)(nil),   // 6: controlplane.StreamRoutesRequest
	(*Route)(nil),                 // 7: controlplane.Route
	(*HeaderMatch)(nil),           // 8: controlplane.HeaderMatch
	(*QueryMatch)(nil),            // 9: controlplane.QueryMatch
	(*RouteRewrite)(nil),          // 10: controlplane.RouteRewrite
	(*RouteAuth)(nil),             // 11: controlplane.RouteAuth
	(*RouteTarget)(nil),           // 12: controlplane.RouteTarget
	(*RouteTable)(nil),            // 13: controlplane.RouteTable
	(*GroupMetrics)(nil),          // 14: controlplane.GroupMetrics
	(*MetricsReport)(nil),         // 15: controlplane.MetricsReport
	(*MetricsReportAck)(nil),      // 16: controlplane.MetricsReportAck
	nil,                           // 17: controlplane.RouteRewrite.SetRequestHeadersEntry
	nil,                           // 18: controlplane.RouteRewrite.SetResponseHeadersEntry
}
var file_proto_controlplane_proto_depIdxs = []int32{
	1,  // 0: controlplane.BackendSet.backends:type_name -> controlplane.Backend
	3,  // 1: controlplane.HealthReport.backends:type_name -> controlplane.BackendHealth
	12, // 2: controlplane.Route.split:type_name -> controlplane.RouteTarget
	10, // 3: controlplane.Route.rewrite:type_name -> controlplane.RouteRewrite
	11, // 4: controlplane.Route.auth:type_name -> controlplane.RouteAuth
	8,  // 5: controlplane.Route.header_matches:type_name -> controlplane.HeaderMatch
	9,  // 6: controlplane.Route.query_matches:type_name -> controlplane.QueryMatch
	17, // 7: controlplane.RouteRewrite.set_request_headers:type_name -> controlplane.RouteRewrite.SetRequestHeadersEntry
	18, // 8: controlplane.RouteRewrite.set_response_headers:type_name -> controlplane.RouteRewrite.SetResponseHeadersEntry
	7,  // 9: controlplane.RouteTable.routes:type_name -> controlplane.Route
	14, // 10: controlplane.MetricsReport.groups:type_name -> controlplane.GroupMetrics
	0,  // 11: controlplane.ControlPlane.StreamBackends:input_type -> controlplane.StreamBackendsRequest
	4,  // 12: controlplane.ControlPlane.ReportHealth:input_type -> controlplane.HealthReport
	6,  // 13: controlplane.ControlPlane.StreamRoutes:input_type -> controlplane.StreamRoutesRequest
	15, // 14: controlplane.ControlPlane.ReportMetrics:input_type -> controlplane.MetricsReport
	2,  // 15: controlplane.ControlPlane.StreamBackends:output_type -> controlplane.BackendSet
	5,  // 16: controlplane.ControlPlane.ReportHealth:output_type -> controlplane.HealthReportAck
	13, // 17: controlplane.ControlPlane.StreamRoutes:output_type -> controlplane.RouteTable
	16, // 18: controlplane.ControlPlane.ReportMetrics:output_type -> controlplane.MetricsReportAck
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_controlplane_proto_init() }
func file_proto_controlplane_proto_init() {
	if File_proto_controlplane_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_controlplane_proto_rawDesc), len(file_proto_controlplane_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_controlplane_proto_goTypes,
		DependencyIndexes: file_proto_controlplane_proto_depIdxs,
		MessageInfos:      file_proto_controlplane_proto_msgTypes,
	}.Build()
	File_proto_controlplane_proto = out.File
	file_proto_controlplane_proto_goTypes = nil
	file_proto_controlplane_proto_depIdxs = nil
}
