// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/controlplane.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControlPlane_StreamBackends_FullMethodName = "/controlplane.ControlPlane/StreamBackends"
	ControlPlane_ReportHealth_FullMethodName   = "/controlplane.ControlPlane/ReportHealth"
	ControlPlane_StreamRoutes_FullMethodName   = "/controlplane.ControlPlane/StreamRoutes"
)

// ControlPlaneClient is the client API for ControlPlane service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ControlPlane is implemented by the control plane and consumed by data
// plane proxy instances. A data plane connects once and receives a stream
// of backend list updates for its group — no polling.
type ControlPlaneClient interface {
	// StreamBackends opens a long-lived stream. The data plane sends its
	// group name once (in the initial request), and receives a new
	// BackendSet every time the control plane's reconciliation loop detects
	// a change for that group.
	StreamBackends(ctx context.Context, in *StreamBackendsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BackendSet], error)
	// ReportHealth is called periodically by a data plane instance to report
	// the current health (as determined by its own local health checker) of
	// every backend it knows about for a group. The control plane has no
	// visibility into backend health on its own — this is how that
	// information flows back, so it can be surfaced in the admin web UI.
	ReportHealth(ctx context.Context, in *HealthReport, opts ...grpc.CallOption) (*HealthReportAck, error)
	// StreamRoutes opens a long-lived stream and pushes the current L7
	// route table, then a new one every time it changes. Unlike
	// StreamBackends, the route table is global (not scoped to a group) —
	// it's how one data plane instance can route different requests to
	// different backend groups from a single listener, rather than being
	// pinned to a single group for its entire lifetime.
	StreamRoutes(ctx context.Context, in *StreamRoutesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RouteTable], error)
}

type controlPlaneClient struct {
	cc grpc.ClientConnInterface
}

func NewControlPlaneClient(cc grpc.ClientConnInterface) ControlPlaneClient {
	return &controlPlaneClient{cc}
}

func (c *controlPlaneClient) StreamBackends(ctx context.Context, in *StreamBackendsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BackendSet], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlPlane_ServiceDesc.Streams[0], ControlPlane_StreamBackends_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamBackendsRequest, BackendSet]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlane_StreamBackendsClient = grpc.ServerStreamingClient[BackendSet]

func (c *controlPlaneClient) ReportHealth(ctx context.Context, in *HealthReport, opts ...grpc.CallOption) (*HealthReportAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthReportAck)
	err := c.cc.Invoke(ctx, ControlPlane_ReportHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) StreamRoutes(ctx context.Context, in *StreamRoutesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RouteTable], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlPlane_ServiceDesc.Streams[1], ControlPlane_StreamRoutes_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRoutesRequest, RouteTable]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlane_StreamRoutesClient = grpc.ServerStreamingClient[RouteTable]

// ControlPlaneServer is the server API for ControlPlane service.
// All implementations must embed UnimplementedControlPlaneServer
// for forward compatibility.
//
// ControlPlane is implemented by the control plane and consumed by data
// plane proxy instances. A data plane connects once and receives a stream
// of backend list updates for its group — no polling.
type ControlPlaneServer interface {
	// StreamBackends opens a long-lived stream. The data plane sends its
	// group name once (in the initial request), and receives a new
	// BackendSet every time the control plane's reconciliation loop detects
	// a change for that group.
	StreamBackends(*StreamBackendsRequest, grpc.ServerStreamingServer[BackendSet]) error
	// ReportHealth is called periodically by a data plane instance to report
	// the current health (as determined by its own local health checker) of
	// every backend it knows about for a group. The control plane has no
	// visibility into backend health on its own — this is how that
	// information flows back, so it can be surfaced in the admin web UI.
	ReportHealth(context.Context, *HealthReport) (*HealthReportAck, error)
	// StreamRoutes opens a long-lived stream and pushes the current L7
	// route table, then a new one every time it changes. Unlike
	// StreamBackends, the route table is global (not scoped to a group) —
	// it's how one data plane instance can route different requests to
	// different backend groups from a single listener, rather than being
	// pinned to a single group for its entire lifetime.
	StreamRoutes(*StreamRoutesRequest, grpc.ServerStreamingServer[RouteTable]) error
	mustEmbedUnimplementedControlPlaneServer()
}

// UnimplementedControlPlaneServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlPlaneServer struct{}

func (UnimplementedControlPlaneServer) StreamBackends(*StreamBackendsRequest, grpc.ServerStreamingServer[BackendSet]) error {
	return status.Error(codes.Unimplemented, "method StreamBackends not implemented")
}
func (UnimplementedControlPlaneServer) ReportHealth(context.Context, *HealthReport) (*HealthReportAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportHealth not implemented")
}
func (UnimplementedControlPlaneServer) StreamRoutes(*StreamRoutesRequest, grpc.ServerStreamingServer[RouteTable]) error {
	return status.Error(codes.Unimplemented, "method StreamRoutes not implemented")
}
func (UnimplementedControlPlaneServer) mustEmbedUnimplementedControlPlaneServer() {}
func (UnimplementedControlPlaneServer) testEmbeddedByValue()                      {}

// UnsafeControlPlaneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlPlaneServer will
// result in compilation errors.
type UnsafeControlPlaneServer interface {
	mustEmbedUnimplementedControlPlaneServer()
}

func RegisterControlPlaneServer(s grpc.ServiceRegistrar, srv ControlPlaneServer) {
	// If the following call panics, it indicates UnimplementedControlPlaneServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlPlane_ServiceDesc, srv)
}

func _ControlPlane_StreamBackends_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamBackendsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlPlaneServer).StreamBackends(m, &grpc.GenericServerStream[StreamBackendsRequest, BackendSet]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlane_StreamBackendsServer = grpc.ServerStreamingServer[BackendSet]

func _ControlPlane_ReportHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).ReportHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_ReportHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).ReportHealth(ctx, req.(*HealthReport))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_StreamRoutes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRoutesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlPlaneServer).StreamRoutes(m, &grpc.GenericServerStream[StreamRoutesRequest, RouteTable]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlane_StreamRoutesServer = grpc.ServerStreamingServer[RouteTable]

// ControlPlane_ServiceDesc is the grpc.ServiceDesc for ControlPlane service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlPlane_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "controlplane.ControlPlane",
	HandlerType: (*ControlPlaneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportHealth",
			Handler:    _ControlPlane_ReportHealth_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamBackends",
			Handler:       _ControlPlane_StreamBackends_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamRoutes",
			Handler:       _ControlPlane_StreamRoutes_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/controlplane.proto",
}
