// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/controlplane.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamBackendsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The backend pool group this data plane instance serves traffic for,
	// e.g. "web-tier" or "api-tier". Lets one control plane serve multiple
	// independent proxy fleets.
	Group string `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	// Human-readable identifier for the connecting data plane instance,
	// used only for control plane logging/observability.
	InstanceId    string `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamBackendsRequest) Reset() {
	*x = StreamBackendsRequest{}
	mi := &file_proto_controlplane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamBackendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamBackendsRequest) ProtoMessage() {}

func (x *StreamBackendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamBackendsRequest.ProtoReflect.Descriptor instead.
func (*StreamBackendsRequest) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{0}
}

func (x *StreamBackendsRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *StreamBackendsRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type Backend struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Address string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // host:port
	// Relative capacity weight for weighted load balancing. Defaults to 1
	// when unset/zero.
	Weight        int32 `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Backend) Reset() {
	*x = Backend{}
	mi := &file_proto_controlplane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Backend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Backend) ProtoMessage() {}

func (x *Backend) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Backend.ProtoReflect.Descriptor instead.
func (*Backend) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{1}
}

func (x *Backend) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Backend) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type BackendSet struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Group    string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Backends []*Backend             `protobuf:"bytes,2,rep,name=backends,proto3" json:"backends,omitempty"`
	// Monotonically increasing version number for this group's backend set.
	// Lets the data plane detect and ignore stale/out-of-order updates.
	Version int64 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	// Load-balancing algorithm the data plane should use to select among
	// these backends: "round_robin" (default, weighted), "least_connections"
	// (weighted by outstanding request count), or "random" (weighted).
	// Unset/unrecognised values fall back to round_robin.
	Algorithm     string `protobuf:"bytes,4,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackendSet) Reset() {
	*x = BackendSet{}
	mi := &file_proto_controlplane_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendSet) ProtoMessage() {}

func (x *BackendSet) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendSet.ProtoReflect.Descriptor instead.
func (*BackendSet) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{2}
}

func (x *BackendSet) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *BackendSet) GetBackends() []*Backend {
	if x != nil {
		return x.Backends
	}
	return nil
}

func (x *BackendSet) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *BackendSet) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

type BackendHealth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // host:port, matches Backend.address
	Healthy       bool                   `protobuf:"varint,2,opt,name=healthy,proto3" json:"healthy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackendHealth) Reset() {
	*x = BackendHealth{}
	mi := &file_proto_controlplane_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendHealth) ProtoMessage() {}

func (x *BackendHealth) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendHealth.ProtoReflect.Descriptor instead.
func (*BackendHealth) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{3}
}

func (x *BackendHealth) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *BackendHealth) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

type HealthReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	InstanceId    string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"` // which data plane instance this report is from
	Backends      []*BackendHealth       `protobuf:"bytes,3,rep,name=backends,proto3" json:"backends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthReport) Reset() {
	*x = HealthReport{}
	mi := &file_proto_controlplane_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthReport) ProtoMessage() {}

func (x *HealthReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthReport.ProtoReflect.Descriptor instead.
func (*HealthReport) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{4}
}

func (x *HealthReport) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *HealthReport) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *HealthReport) GetBackends() []*BackendHealth {
	if x != nil {
		return x.Backends
	}
	return nil
}

type HealthReportAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthReportAck) Reset() {
	*x = HealthReportAck{}
	mi := &file_proto_controlplane_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthReportAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthReportAck) ProtoMessage() {}

func (x *HealthReportAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthReportAck.ProtoReflect.Descriptor instead.
func (*HealthReportAck) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{5}
}

type StreamRoutesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human-readable identifier for the connecting data plane instance,
	// used only for control plane logging/observability.
	InstanceId    string `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRoutesRequest) Reset() {
	*x = StreamRoutesRequest{}
	mi := &file_proto_controlplane_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRoutesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRoutesRequest) ProtoMessage() {}

func (x *StreamRoutesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRoutesRequest.ProtoReflect.Descriptor instead.
func (*StreamRoutesRequest) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{6}
}

func (x *StreamRoutesRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type Route struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Host to match, exact string. "*" or empty matches any host — a
	// data plane with a single route relying on the default group
	// shouldn't need to specify a host at all.
	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	// Path prefix to match, e.g. "/api/". "/" matches every path.
	// Evaluated as a literal prefix, not a pattern language — kept
	// deliberately simple for a first cut of L7 routing.
	PathPrefix string `protobuf:"bytes,2,opt,name=path_prefix,json=pathPrefix,proto3" json:"path_prefix,omitempty"`
	// HTTP methods this rule applies to. Empty means any method.
	Methods []string `protobuf:"bytes,3,rep,name=methods,proto3" json:"methods,omitempty"`
	// Backend group a matching request is proxied to.
	TargetGroup string `protobuf:"bytes,4,opt,name=target_group,json=targetGroup,proto3" json:"target_group,omitempty"`
	// Display name/comment for the admin UI; not evaluated.
	Name          string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_proto_controlplane_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{7}
}

func (x *Route) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Route) GetPathPrefix() string {
	if x != nil {
		return x.PathPrefix
	}
	return ""
}

func (x *Route) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

func (x *Route) GetTargetGroup() string {
	if x != nil {
		return x.TargetGroup
	}
	return ""
}

func (x *Route) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RouteTable struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Rules in evaluation order — the data plane checks them top to bottom
	// and uses the first match. A request matching no rule falls back to
	// the data plane's own -group flag, so an instance with an empty (or
	// unreachable) route table keeps behaving exactly as it did before L7
	// routing existed.
	Routes []*Route `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	// Monotonically increasing version number, mirroring BackendSet.version
	// — lets the data plane detect and ignore stale/out-of-order updates.
	Version       int64 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteTable) Reset() {
	*x = RouteTable{}
	mi := &file_proto_controlplane_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteTable) ProtoMessage() {}

func (x *RouteTable) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteTable.ProtoReflect.Descriptor instead.
func (*RouteTable) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{8}
}

func (x *RouteTable) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *RouteTable) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_proto_controlplane_proto protoreflect.FileDescriptor

const file_proto_controlplane_proto_rawDesc = "" +
	"\n" +
	"\x18proto/controlplane.proto\x12\fcontrolplane\"N\n" +
	"\x15StreamBackendsRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\";\n" +
	"\aBackend\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\x05R\x06weight\"\x8d\x01\n" +
	"\n" +
	"BackendSet\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x121\n" +
	"\bbackends\x18\x02 \x03(\v2\x15.controlplane.BackendR\bbackends\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\x12\x1c\n" +
	"\talgorithm\x18\x04 \x01(\tR\talgorithm\"C\n" +
	"\rBackendHealth\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x18\n" +
	"\ahealthy\x18\x02 \x01(\bR\ahealthy\"~\n" +
	"\fHealthReport\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x127\n" +
	"\bbackends\x18\x03 \x03(\v2\x1b.controlplane.BackendHealthR\bbackends\"\x11\n" +
	"\x0fHealthReportAck\"6\n" +
	"\x13StreamRoutesRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\"\x8d\x01\n" +
	"\x05Route\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x1f\n" +
	"\vpath_prefix\x18\x02 \x01(\tR\n" +
	"pathPrefix\x12\x18\n" +
	"\amethods\x18\x03 \x03(\tR\amethods\x12!\n" +
	"\ftarget_group\x18\x04 \x01(\tR\vtargetGroup\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\"S\n" +
	"\n" +
	"RouteTable\x12+\n" +
	"\x06routes\x18\x01 \x03(\v2\x13.controlplane.RouteR\x06routes\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion2\xfb\x01\n" +
	"\fControlPlane\x12Q\n" +
	"\x0eStreamBackends\x12#.controlplane.StreamBackendsRequest\x1a\x18.controlplane.BackendSet0\x01\x12I\n" +
	"\fReportHealth\x12\x1a.controlplane.HealthReport\x1a\x1d.controlplane.HealthReportAck\x12M\n" +
	"\fStreamRoutes\x12!.controlplane.StreamRoutesRequest\x1a\x18.controlplane.RouteTable0\x01B&Z$github.com/Josephfell/Jbalance/protob\x06proto3"

var (
	file_proto_controlplane_proto_rawDescOnce sync.Once
	file_proto_controlplane_proto_rawDescData []byte
)

func file_proto_controlplane_proto_rawDescGZIP() []byte {
	file_proto_controlplane_proto_rawDescOnce.Do(func() {
		file_proto_controlplane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_controlplane_proto_rawDesc), len(file_proto_controlplane_proto_rawDesc)))
	})
	return file_proto_controlplane_proto_rawDescData
}

var file_proto_controlplane_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_controlplane_proto_goTypes = []any{
	(*StreamBackendsRequest)(nil), // 0: controlplane.StreamBackendsRequest
	(*Backend)(nil),               // 1: controlplane.Backend
	(*BackendSet)(nil),            // 2: controlplane.BackendSet
	(*BackendHealth)(nil),         // 3: controlplane.BackendHealth
	(*HealthReport)(nil),          // 4: controlplane.HealthReport
	(*HealthReportAck)(nil),       // 5: controlplane.HealthReportAck
	(*StreamRoutesRequest)(nil),   // 6: controlplane.StreamRoutesRequest
	(*Route)(nil),                 // 7: controlplane.Route
	(*RouteTable)(nil),            // 8: controlplane.RouteTable
}
var file_proto_controlplane_proto_depIdxs = []int32{
	1, // 0: controlplane.BackendSet.backends:type_name -> controlplane.Backend
	3, // 1: controlplane.HealthReport.backends:type_name -> controlplane.BackendHealth
	7, // 2: controlplane.RouteTable.routes:type_name -> controlplane.Route
	0, // 3: controlplane.ControlPlane.StreamBackends:input_type -> controlplane.StreamBackendsRequest
	4, // 4: controlplane.ControlPlane.ReportHealth:input_type -> controlplane.HealthReport
	6, // 5: controlplane.ControlPlane.StreamRoutes:input_type -> controlplane.StreamRoutesRequest
	2, // 6: controlplane.ControlPlane.StreamBackends:output_type -> controlplane.BackendSet
	5, // 7: controlplane.ControlPlane.ReportHealth:output_type -> controlplane.HealthReportAck
	8, // 8: controlplane.ControlPlane.StreamRoutes:output_type -> controlplane.RouteTable
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_controlplane_proto_init() }
func file_proto_controlplane_proto_init() {
	if File_proto_controlplane_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_controlplane_proto_rawDesc), len(file_proto_controlplane_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_controlplane_proto_goTypes,
		DependencyIndexes: file_proto_controlplane_proto_depIdxs,
		MessageInfos:      file_proto_controlplane_proto_msgTypes,
	}.Build()
	File_proto_controlplane_proto = out.File
	file_proto_controlplane_proto_goTypes = nil
	file_proto_controlplane_proto_depIdxs = nil
}
